routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->middleware('auth')->group(function(){
    Route::get('/', [RoleController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-role');
    Route::get('/{role}', [RoleController::class, 'show'])
        ->name('show')
        ->where('role', '[0-9]+')
        ->middleware('permission:index-role');
    Route::get('/search', [RoleController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-role');
    Route::get('/create', [RoleController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-role');
    Route::post('/', [RoleController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-role');
    Route::get('/{role}/edit', [RoleController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-role']);
    Route::put('/{role}', [RoleController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-role']);
    Route::delete('/{role}', [RoleController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-role', 'check.superadmin']);
});

Route::prefix('users')->name('users.')->middleware('auth')->group(function(){
    Route::get('/', [UserController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-user');
    Route::get('/{user}', [UserController::class, 'show'])
        ->name('show')
        ->where('user', '[0-9]+')
        ->middleware('permission:index-user');
    Route::get('/search', [UserController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-user');;
    Route::get('/create', [UserController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-user');
    Route::post('/', [UserController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-user');
    Route::get('/{user}/edit', [UserController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-user']);
    Route::put('/{user}', [UserController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-user']);
    Route::delete('/{user}', [UserController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-user', 'check.superadmin', 'check.user']);
});
Route::prefix('categories')->name('categories.')->middleware('auth')->group(function() {
    Route::get('/', [CategoryController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-category');
    Route::get('/list', [CategoryController::class, 'list'])
        ->name('list')
        ->middleware('permission:index-category');
    Route::get('/getParentCategories', [CategoryController::class, 'getParentCategories'])
        ->name('getParentCategories')
        ->middleware('permission:index-category');
    Route::post('/', [CategoryController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-category');
    Route::get('/{category}/edit', [CategoryController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-category');
    Route::put('/{category}', [CategoryController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-category');
    Route::delete('/{category}', [CategoryController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-category');
});
Route::prefix('products')->name('products.')->middleware('auth')->group(function() {
    Route::get('/', [ProductController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-product');
    Route::get('/{product}', [ProductController::class, 'show'])
        ->name('show')
        ->where('product', '[0-9]+')
        ->middleware('permission:index-product');
    Route::get('/search', [ProductController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-product');
    Route::get('/create', [ProductController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-product');
    Route::post('/', [ProductController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-product');
    Route::get('/{product}/edit', [ProductController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-product');
    Route::put('/{product}', [ProductController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-product');
    Route::delete('/{product}', [ProductController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-product');
});
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table = 'roles';

    protected $fillable = [
        'name',
        'display_name',
    ];

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('display_name', 'LIKE', "%{$name}%") : null;
    }

    public function scopeWithNameNotSuperAdmin($query)
    {
        return $query->where('name', '!=', 'super-admin');
    }

    public function assignPermissions($permissionIds)
    {
        return $this->permissions()->attach($permissionIds);
    }

    public function syncPermissions($permissionIds)
    {
        return $this->permissions()->sync($permissionIds);
    }

    public function users()
    {
        return $this->belongsToMany(
            User::class,
            'user_role',
            'role_id',
            'user_id'
        );
    }

    public function permissions()
    {
        return $this->belongsToMany(
            Permission::class,
            'role_permission',
            'role_id',
            'permission_id'
        );
    }

    public function hasPermission($permissionName)
    {
        return $this->permissions->contains('name', $permissionName);
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\CreateRoleRequest;
use App\Http\Requests\Role\RoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Services\PermissionService;
use App\Services\RoleService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class RoleController extends Controller
{
    protected $roleService;
    public function __construct(RoleService $roleService)
    {
        $this->roleService = $roleService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = $this->roleService->search($request);
        $request->flash();
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoleRequest $request)
    {
        $this->roleService->create($request);
        return redirect()->route('roles.index')
            ->with('message', 'Create Role Success !!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = $this->roleService->findById($id);
        return view('admin.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = $this->roleService->findById($id);
        return view('admin.roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, $id)
    {
        $this->roleService->update($request, $id);
        return redirect()->route('roles.index')
            ->with('message', 'Update Role Success !!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->roleService->delete($id);
        return redirect()->route('roles.index')
            ->with('message', 'Delete Role Success !!!');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')
@section('content')
    <!-- Header -->
    <div class="header bg-primary pb-6 pt-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Role</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Create New Role</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header border-0">
                        <h2 class="mb-0 pl-5">Create New Role</h2>
                        <form action="{{ route('roles.store') }}" method="post" class="pl-5 pr-5 pt-3">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name :</label>
                                <input type="text" class="form-control" name="name" placeholder="Name"
                                       value="{{ old('name') }}">
                                @if($errors->has('name'))
                                    <p class="text-danger">{{$errors->first('name')}}</p>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="display_name">Display Name :</label>
                                <input type="text" class="form-control" name="display_name" placeholder="Display Name"
                                       value="{{ old('display_name') }}">
                                @if($errors->has('display_name'))
                                    <p class="text-danger">{{$errors->first('display_name')}}</p>
                                @endif
                            </div>
                            <div>
                                <div class="row">
                                    <div class="col-sm-2">Permission:</div>
                                    <div class="col-10">
                                        <input class="form-check-input permission-select-all" type="checkbox">
                                        <label class="form-check-label">
                                            Select all
                                        </label>
                                    </div>
                                </div>
                                <br>
                                <h4>Role</h4>
                                <div class="form-check">
                                    <input class="form-check-input selectAllPermission" type="checkbox" id="role-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($rolePermissions as $rolePermission)
                                    <div class="form-check form-check-inline rolePerCheck">
                                        <input class="form-check-input rolePermission" type="checkbox"
                                               value="{{ $rolePermission->id }}"
                                               name="permission_ids[]">
                                        <label class="form-check-label">
                                            {{ $rolePermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                                <h4>User</h4>
                                <div class="form-check">
                                    <input class="form-check-input selectAllPermission" type="checkbox" id="user-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($userPermissions as $userPermission)
                                    <div class="form-check form-check-inline userPerCheck">
                                        <input class="form-check-input userPermission" type="checkbox"
                                               value="{{ $userPermission->id }}"
                                               name="permission_ids[]">
                                        <label class="form-check-label">
                                            {{ $userPermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                                <h4>Category</h4>
                                <div class="form-check">
                                    <input class="form-check-input selectAllPermission" type="checkbox" id="category-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($categoryPermissions as $categoryPermission)
                                    <div class="form-check form-check-inline categoryPerCheck">
                                        <input class="form-check-input categoryPermission" type="checkbox"
                                               value="{{ $categoryPermission->id }}"
                                               name="permission_ids[]">
                                        <label class="form-check-label">
                                            {{ $categoryPermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                                <h4>Product</h4>
                                <div class="form-check">
                                    <input class="form-check-input selectAllPermission" type="checkbox" id="product-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($productPermissions as $productPermission)
                                    <div class="form-check form-check-inline productPerCheck">
                                        <input class="form-check-input productPermission" type="checkbox"
                                               value="{{ $productPermission->id }}"
                                               name="permission_ids[]">
                                        <label class="form-check-label">
                                            {{ $productPermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                            <button type="submit" class="btn btn-success mt-3">Create</button>
                            <a href="{{ route('roles.index') }}" class="btn btn-primary float-right mt-3"><i
                                    class="fas fa-home"></i>&nbsp;&nbsp;Home</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script type="module" src="{{ asset('admin/js/role.js') }}"></script>
@endpush

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')
@section('content')
    <!-- Header -->
    <div class="header bg-primary pb-6 pt-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Role</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Edit Role</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header border-0">
                        <h2 class="mb-0 pl-5">Edit Role {{ $role->display_name }}</h2>
                        <form action="{{ route('roles.update', $role->id) }}" method="post" class="pl-5 pr-5 pt-3">
                            @csrf
                            @method('put')
                            <div class="form-group">
                                <label for="name">Name :</label>
                                <input type="text" class="form-control" name="name" placeholder="Name"
                                       value="{{$role->name}}">
                                @if($errors->has('name'))
                                    <p class="text-danger">{{$errors->first('name')}}</p>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="display_name">Display Name :</label>
                                <input type="text" class="form-control" name="display_name"
                                       placeholder="Display Name" value="{{$role->display_name}}">
                                @if($errors->has('display_name'))
                                    <p class="text-danger">{{$errors->first('display_name')}}</p>
                                @endif
                            </div>
                            <div>
                                <div class="row">
                                    <div class="col-sm-2">Permission:</div>
                                </div>
                                <br>
                                <h4>Role</h4>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="role-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($rolePermissions as $rolePermission)
                                    <div class="form-check form-check-inline rolePerCheck">
                                        <input class="form-check-input rolePermission" type="checkbox"
                                               value="{{ $rolePermission->id }}" name="permission_ids[]"
                                               @if(in_array($rolePermission->id,$role->permissions()->pluck('id')->toArray())) checked
                                               @endif>
                                        <label class="form-check-label">
                                            {{ $rolePermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                                <h4>User</h4>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="user-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($userPermissions as $userPermission)
                                    <div class="form-check form-check-inline userPerCheck">
                                        <input class="form-check-input userPermission" type="checkbox"
                                               value="{{ $userPermission->id }}" name="permission_ids[]"
                                               @if(in_array($userPermission->id,$role->permissions()->pluck('id')->toArray())) checked
                                               @endif
                                        >
                                        <label class="form-check-label">
                                            {{ $userPermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                                <h4>Category</h4>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="category-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($categoryPermissions as $categoryPermission)
                                    <div class="form-check form-check-inline categoryPerCheck">
                                        <input class="form-check-input categoryPermission" type="checkbox"
                                               value="{{ $categoryPermission->id }}" name="permission_ids[]"
                                               @if(in_array($categoryPermission->id,$role->permissions()->pluck('id')->toArray())) checked
                                               @endif
                                        >
                                        <label class="form-check-label">
                                            {{ $categoryPermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                                <h4>Product</h4>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="product-select-all">
                                    <label class="form-check-label">
                                        Select all
                                    </label>
                                </div>
                                @foreach($productPermissions as $productPermission)
                                    <div class="form-check form-check-inline productPerCheck">
                                        <input class="form-check-input productPermission" type="checkbox"
                                               value="{{ $productPermission->id }}" name="permission_ids[]"
                                               @if(in_array($productPermission->id,$role->permissions()->pluck('id')->toArray())) checked
                                               @endif
                                        >
                                        <label class="form-check-label">
                                            {{ $productPermission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                            <br>
                            <button type="submit" class="btn btn-success">Update</button>
                            <a href="{{ route('roles.index') }}" class="btn btn-primary float-right"><i
                                    class="fas fa-home"></i>&nbsp;&nbsp;Home</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script type="module" src="{{ asset('admin/js/role.js') }}"></script>
@endpush

resources/views/admin/roles/show.blade.php
@extends('layouts.app')
@section('content')
    <!-- Header -->
    <div class="header bg-primary pb-6 pt-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Role</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Role Detail</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a class="nav-link active bg-info">Role Id: {{ $role->id }}</a>
                            </li>
                        </ul>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <h5 class="card-title">
                            <span class="font-weight-bold">Display Name :</span>&nbsp;&nbsp;
                            <span class="badge bg-success">{{ $role->display_name }}</span>
                        </h5>
                        <br><br>
                        <p class="card-text">
                            User Count : {{ $role->users()->count() }}
                        </p>
                        <h5>Permission</h5>

                        @foreach($role->permissions as $permission)
                            <span class="badge badge-info">{{$permission->display_name}}</span>
                        @endforeach
                        <br>
                        <br>
                        <a href="{{ route('roles.edit',$role->id) }}" class="btn btn-warning">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-pencil" viewBox="0 0 16 16">
                                <path
                                    d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg>
                        </a>
                        <a href="{{ route('roles.index') }}" class="btn btn-primary float-right"><i
                                class="fas fa-home"></i>&nbsp;&nbsp;Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection