routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->middleware('auth')->group(function(){
    Route::get('/', [RoleController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-role');
    Route::get('/{role}', [RoleController::class, 'show'])
        ->name('show')
        ->where('role', '[0-9]+')
        ->middleware('permission:index-role');
    Route::get('/search', [RoleController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-role');
    Route::get('/create', [RoleController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-role');
    Route::post('/', [RoleController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-role');
    Route::get('/{role}/edit', [RoleController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-role']);
    Route::put('/{role}', [RoleController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-role']);
    Route::delete('/{role}', [RoleController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-role', 'check.superadmin']);
});

Route::prefix('users')->name('users.')->middleware('auth')->group(function(){
    Route::get('/', [UserController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-user');
    Route::get('/{user}', [UserController::class, 'show'])
        ->name('show')
        ->where('user', '[0-9]+')
        ->middleware('permission:index-user');
    Route::get('/search', [UserController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-user');;
    Route::get('/create', [UserController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-user');
    Route::post('/', [UserController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-user');
    Route::get('/{user}/edit', [UserController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-user']);
    Route::put('/{user}', [UserController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-user']);
    Route::delete('/{user}', [UserController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-user', 'check.superadmin', 'check.user']);
});
Route::prefix('categories')->name('categories.')->middleware('auth')->group(function() {
    Route::get('/', [CategoryController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-category');
    Route::get('/list', [CategoryController::class, 'list'])
        ->name('list')
        ->middleware('permission:index-category');
    Route::get('/getParentCategories', [CategoryController::class, 'getParentCategories'])
        ->name('getParentCategories')
        ->middleware('permission:index-category');
    Route::post('/', [CategoryController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-category');
    Route::get('/{category}/edit', [CategoryController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-category');
    Route::put('/{category}', [CategoryController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-category');
    Route::delete('/{category}', [CategoryController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-category');
});
Route::prefix('products')->name('products.')->middleware('auth')->group(function() {
    Route::get('/', [ProductController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-product');
    Route::get('/{product}', [ProductController::class, 'show'])
        ->name('show')
        ->where('product', '[0-9]+')
        ->middleware('permission:index-product');
    Route::get('/search', [ProductController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-product');
    Route::get('/create', [ProductController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-product');
    Route::post('/', [ProductController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-product');
    Route::get('/{product}/edit', [ProductController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-product');
    Route::put('/{product}', [ProductController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-product');
    Route::delete('/{product}', [ProductController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-product');
});
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-delete" aria-controls="sidenav-delete" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/blue.png" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('users.edit', auth()->user()->id) }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-delete" aria-controls="sidenav-delete" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <!-- Heading -->
            <h6 class="navbar-heading text-muted">Tài khoản</h6>
            <ul class="navbar-nav">
                @hasPermission('index-role')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('roles.index') }}">
                        <i class="ni ni-briefcase-24 text-primary"></i> {{ __('Role') }}
                    </a>
                </li>
                @endhasPermission
                @hasPermission('index-user')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('users.index') }}">
                        <i class="ni ni-single-02 text-blue"></i> {{ __('User') }}
                    </a>
                </li>
                @endhasPermission
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading -->
            <h6 class="navbar-heading text-muted">Sản phẩm</h6>
            <!-- Navigation -->
            <ul class="navbar-nav mb-md-3">
                @hasPermission('index-category')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('categories.index') }}">
                        <i class="ni ni-books text-blue"></i> {{ __('Category') }}
                    </a>
                </li>
                @endhasPermission
                @hasPermission('index-product')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('products.index') }}">
                        <i class="ni ni-laptop text-blue"></i> {{ __('Product') }}
                    </a>
                </li>
                @endhasPermission
            </ul>
        </div>
    </div>
</nav>