routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->middleware('auth')->group(function(){
    Route::get('/', [RoleController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-role');
    Route::get('/{role}', [RoleController::class, 'show'])
        ->name('show')
        ->where('role', '[0-9]+')
        ->middleware('permission:index-role');
    Route::get('/search', [RoleController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-role');
    Route::get('/create', [RoleController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-role');
    Route::post('/', [RoleController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-role');
    Route::get('/{role}/edit', [RoleController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-role']);
    Route::put('/{role}', [RoleController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-role']);
    Route::delete('/{role}', [RoleController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-role', 'check.superadmin']);
});

Route::prefix('users')->name('users.')->middleware('auth')->group(function(){
    Route::get('/', [UserController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-user');
    Route::get('/{user}', [UserController::class, 'show'])
        ->name('show')
        ->where('user', '[0-9]+')
        ->middleware('permission:index-user');
    Route::get('/search', [UserController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-user');;
    Route::get('/create', [UserController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-user');
    Route::post('/', [UserController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-user');
    Route::get('/{user}/edit', [UserController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-user']);
    Route::put('/{user}', [UserController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-user']);
    Route::delete('/{user}', [UserController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-user', 'check.superadmin', 'check.user']);
});
Route::prefix('categories')->name('categories.')->middleware('auth')->group(function() {
    Route::get('/', [CategoryController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-category');
    Route::get('/list', [CategoryController::class, 'list'])
        ->name('list')
        ->middleware('permission:index-category');
    Route::get('/getParentCategories', [CategoryController::class, 'getParentCategories'])
        ->name('getParentCategories')
        ->middleware('permission:index-category');
    Route::post('/', [CategoryController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-category');
    Route::get('/{category}/edit', [CategoryController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-category');
    Route::put('/{category}', [CategoryController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-category');
    Route::delete('/{category}', [CategoryController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-category');
});
Route::prefix('products')->name('products.')->middleware('auth')->group(function() {
    Route::get('/', [ProductController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-product');
    Route::get('/{product}', [ProductController::class, 'show'])
        ->name('show')
        ->where('product', '[0-9]+')
        ->middleware('permission:index-product');
    Route::get('/search', [ProductController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-product');
    Route::get('/create', [ProductController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-product');
    Route::post('/', [ProductController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-product');
    Route::get('/{product}/edit', [ProductController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-product');
    Route::put('/{product}', [ProductController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-product');
    Route::delete('/{product}', [ProductController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-product');
});
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $appends = ['parent_category_name'];

    protected $table = 'categories';

    protected $fillable = [
        'parent_id',
        'name',
    ];

    public function parentCategory()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }


    public function getParentCategoryNameAttribute()
    {
        return $this->parentCategory ? $this->parentCategory->name : null;
    }

    public function scopeWithParentCategories($query)
    {
        return $query->whereNull('parent_id');
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'LIKE', "%{$name}%") : null;
    }

    public function scopeWithParentId($query, $parentId)
    {
        return $parentId ? $query->where('parent_id', $parentId) : null;
    }
    public function products()
    {
        return $this->belongsToMany(
            Product::class,
            'category_product',
            'category_id',
            'product_id'
        );
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\CategoryRequest;
use App\Http\Requests\Category\CreateCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Http\Resources\CategoryCollection;
use App\Http\Resources\CategoryResource;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use function Symfony\Component\Translation\t;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        return view('admin.categories.index');
    }

    public function list(Request $request)
    {
        $categories = $this->categoryService->search($request);
        return view('admin.categories.list', compact('categories'));
    }

    public function getParentCategories()
    {
        $parentCategories = $this->categoryService->getParentCategories();
        $parentCategoriesCollection = new CategoryCollection($parentCategories);
        return $this->sentSuccessResponse($parentCategoriesCollection,
            'success', Response::HTTP_OK);
    }

    public function store(CreateCategoryRequest $request)
    {
        $category = $this->categoryService->create($request);
        $categoryResource = new CategoryResource($category);
        return $this->sentSuccessResponse($categoryResource, 'success', Response::HTTP_OK);
    }

    public function edit($id)
    {
        $category = $this->categoryService->findById($id);
        $parentCategories = $this->categoryService->getParentCategories();
        $categoryResource = new CategoryResource($category);
        $parentCategoriesResource = new CategoryCollection($parentCategories);
        return $this->sentSuccessResponse([
            'category' => $categoryResource,
            'parentCategories' => $parentCategoriesResource
        ],
            'success',
            Response::HTTP_OK);
    }

    public function update(UpdateCategoryRequest $request, $id)
    {
        $category = $this->categoryService->update($request, $id);
        $categoryResource = new CategoryResource($category);
        return $this->sentSuccessResponse($categoryResource, 'success', Response::HTTP_OK);
    }

    public function destroy($id)
    {
        $category = $this->categoryService->delete($id);
        $categoryResource = new CategoryResource($category);
        return $this->sentSuccessResponse($categoryResource, 'success', Response::HTTP_OK);
    }
}

resources/views/admin/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <!-- Modal Create -->
    <div class="modal fade" id="CreateCategoryModal"
         tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="createCategoryForm">
                        <div class="form-group mb-3">
                            <label for="">Name :</label>
                            <input type="text" class="form-control" id="nameCreate" name="name">
                            <span class="text-danger" id="create_name_error"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label for="">Parent Category :</label>
                            <select class="custom-select parent-categories" id="parentIdCreate"
                                    data-action="{{route('categories.getParentCategories')}}" name="parent_id">
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary closeForm"
                            data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary createCategory"
                            data-action="{{ route('categories.store') }}">Save
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Edit -->
    <div class="modal fade" id="EditCategoryModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="updateCategoryForm">
                        <div class="form-group mb-3">
                            <label for="">Name :</label>
                            <input type="text" class="name form-control" id="nameUpdate" name="name">
                            <span class="text-danger" id="update_name_error"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label for="">Parent Category :</label>
                            <select class="custom-select parent-categories" name="parent_id" id="parentIdUpdate">
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary closeForm"
                            data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary updateCategory"
                            id="updateCategorySubmit">Update</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Header -->
    <div class="header bg-primary pb-6 pt-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="#">Category</a></li>
                                <li class="breadcrumb-item active" aria-current="page">List</li>
                            </ol>
                        </nav>
                    </div>
                    @hasPermission('create-category')
                    <div class="col-lg-6 col-5 text-right">
                        <a href="" class="btn btn-default" data-toggle="modal"
                           data-target="#CreateCategoryModal">Create New Category</a>
                    </div>
                    @endhasPermission
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <div id="list" data-action="{{route('categories.list')}}">
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script  type="module" src="{{ asset('admin/js/category.js') }}"></script>
@endpush

resources/views/admin/categories/list.blade.php
<div id="list" data-action="{{route('categories.list')}}">
    <div class="card">
        <!-- Card header -->
        <div class="card-header border-0">
            <h3 class="mb-0">Category</h3>

        </div>
        <!-- Light table -->
        <div class="table-responsive">
            <table class="table align-items-center table-flush table-hover">
                <thead class="thead-light">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Main Category</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody class="list">
                @forelse($categories as $category)
                    <tr>
                        <th scope="row">{{ $category->id }}</th>
                        <td class="name text-sm"><strong>{{ $category->name }}</strong></td>
                        <td>
                            {{ $category->parent_category_name }}
                        </td>
                        <td class="text-left">
                            <div class="dropdown">
                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    @hasPermission('edit-category')
                                    <a class="dropdown-item editCategory" data-action="{{route('categories.edit', $category->id)}}">Edit</a>
                                    @endhasPermission
                                    @hasPermission('delete-category')
                                    <a class="dropdown-item deleteCategory" data-action="{{route('categories.destroy', $category->id)}}">Delete</a>
                                    @endhasPermission
                                </div>
                            </div>
                        </td>
                    </tr>
                @empty
                    <p class="font-weight-bold"> -- NOT FOUND DATA -- </p>
                @endforelse
                </tbody>
            </table>
        </div>
        <!-- Card footer -->
        <div class="card-footer py-4">
            {{ $categories->links() }}
        </div>
    </div>
</div>